language: python
python: 3.8

dist: xenial

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: always